config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  resources :posts_admin do
    member do
      get :publish
      get :unpublish
    end
  end
  resources :posts, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base

  POST_STATUSES = [
    STATUS_PUBLISHED = 'published',
    STATUS_UNPUBLISHED = 'unpublished'
  ]

  scope :published, -> { where(published: Post::STATUS_PUBLISHED) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_admin_controller.rb
class PostsAdminController < ApplicationController

  before_action :find_post, only: [:edit, :update, :show, :destroy]


  def index
    @posts = Post.order('id DESC')
  end

  def show
    
  end

  def new
    @post = Post.create
    redirect_to edit_posts_admin_path(@post)
  end

  def create
    
  end

  def edit

  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to posts_admin_index_path
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if find_post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_admin_index_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  # Publish action makes the post visible to the public
  def publish
    @post = find_post
    if @post.update_attribute(:published, Post::STATUS_PUBLISHED)
      flash[:notice] = "Successfully published post!"
      redirect_to posts_admin_index_path
    else
      flash[:alert] = "Error publishing post!"
      render :index
    end
  end

  # Unpublish action makes the post invisible to the public
  def unpublish
    @post = find_post
    if @post.update_attribute(:published, Post::STATUS_UNPUBLISHED)
      flash[:notice] = "Successfully unpublished post!"
      redirect_to posts_admin_index_path
    else
      flash[:alert] = "Error unpublishing post!"
      render :index
    end
  end

  private

  def post_params
    params.require(:post).permit(:post_id, :title, :body, post_attachments_attributes: [:post_image])
  end

  def find_post
    @post = Post::find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show]

  def index
    @posts = Post.order('id DESC').published #.page(params[:page])
  end

  # The show action renders the individual post after retrieving the the id
  def show
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsBlogWithAdmin
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/index.haml
.posts.container
  .post__header
    .jumbotron
      %h1 Rails Blog with Admin
      %p Styled with Bootstrap
      %p.pull-right ... and I was in a purple kind of mood.

  .row.posts__button-row
    = link_to 'Post Administration', posts_admin_index_path, class: 'btn btn-purple'
    = link_to "New Post", new_posts_admin_path, class: 'btn btn-purple'

  .row
    .col-md-2
      - if @posts
        - @posts.each do |post|
          %p= post.title
      - else
        %p No posts yet. :(
    
    .col-md-10  
      .panel.posts__panel
        .panel-heading
          %h1= @posts.first.title 
        .panel-body
          %p= raw @posts.first.body

app/views/posts/show.haml
.blog-content.container
  .row.blog
    -# -if current_user
    = link_to "Edit", edit_posts_admin_path(@post), id: "edit", class: 'adminBtn btn'
  %h2.text-center= @post.title
  %h5.text-center= @post.created_at.strftime('%b %d, %Y')
  %div= raw @post.body

app/views/posts_admin/_form.haml
= simple_form_for @post, url: posts_admin_path do |f|
  - if @post.errors.any?
    .error_explanation
      %h2
        = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li
            = msg

  %input#postId{:type => "hidden", :value => "<%= @post.id"}

  .form-group
    = f.input :title, input_html: { class: 'form-control'}
  
  .form-group
    = f.input :body, input_html: { class: 'summernote'}
  
  .actions
    = f.submit class: 'btn btn-default'
    = link_to 'Show', @post, class: 'btn btn-default' if @post.persisted?
    = link_to 'Back', posts_path, class: 'btn btn-default'
    = link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

:javascript
  $( document ).ready(function() {
    $('.summernote').summernote();
  });

app/views/posts_admin/edit.haml
%div.container
  %h2{class:"blog"} Edit Post
  =render partial: 'posts_admin/form'

app/views/posts_admin/index.haml
%div.postsAdmin.container
  %h3 Blog Post Administration Page
  = link_to "New Post", new_posts_admin_path, class: 'btn btn-default'
  %h5 Manage previous posts
  %table
    %tr
      %td TITLE
      %td CREATED DATE
      %td PREVIEW
      %td
      %td
      %td
      %td CURRENT STATE

    - @posts.each do |post| 
      %tr
        %td= link_to post.title, post_path(post)
        %td= post.created_at.strftime('%b %d, %Y')
        %td
          -if post.body
            = sanitize(post.body, :tags=>[]).truncate(25, :separator => " ")
        %td
          = link_to 'Publish', publish_posts_admin_path(post), class: 'btn publishBtn'
        %td
          = link_to 'Unpublish', unpublish_posts_admin_path(post), class: 'btn unpublishBtn'
        %td
          = button_to 'Delete', posts_admin_path(post), method: :delete, data: { confirm: 'Delete post, are you sure?' }, class: 'btn destroyBtn'
        %td= post.published.titleize

app/views/posts_admin/new.haml
%div.container
  %h2 Create New Post
  =render partial: 'posts_admin/form'